### PR TITLE
Track vis

### PR DESCRIPTION
**Pull request by Will-Dinicola**
Yo can I get the code I copy pasted it before and changed

### CODE REVIEW

**Comment by jackschedel** [comment]
@Will-Dinicola why did u make a pull request when the most recent commit title literally says it isn't working lmfao

**Comment by Will-Dinicola** [comment]
Wdym doesn’t pull take from main

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Seth10001** [comment]
> Wdym doesn’t pull take from main Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

@Will-Dinicola He's saying that the commit title at the time was "track vis better but not working" https://github.com/Solar-Gators/strategy-simulation/pull/1/commits/b19f10efcbc4c248d54dae8f4768d4565ff0d7ad

Ya'll should write some tests haha

**Comment by Will-Dinicola** [comment]
> @Will-Dinicola why did u make a pull request when the most recent commit title literally says it isn't working lmfao

**Comment by Will-Dinicola** [comment]
> @Will-Dinicola why did u make a pull request when the most recent commit title literally says it isn't working lmfao

I understand it now the pull request is like for the main branch to pull my changes... instead I commit and then I push to the track-vis branch right? Assuming I want other strategy members to be able to see it and for the track-vis to be updated but it is not yet ready for merging into the main branch.

**Comment by jackschedel** [comment]
@Will-Dinicola correct. Sorry I didn't really explain pull requests when I gave my git overview, but it seems you understand it now.

**Comment by jackschedel** [comment]
@Seth10001 
> Ya'll should write some tests haha

The project isn't really far enough along for that yet, I will once it's in a semi-flushed-out state

**Pull request closed without merging**
